initial commit
codex-team/capella.go pull request #1
Opened 2018-02-11 17:38 UTC by khaydarov

2018-02-12 08:27 UTC, n0str commented on .gitignore
> +.idea/vcs.xml
idea и так в игноре

2018-02-12 09:07 UTC, neSpecc requested changes

2018-02-12 09:07 UTC, neSpecc commented on capella.go
> +package capella
можно сгенерить документацию с помощью godoc

https://blog.golang.org/godoc-documenting-go-code

2018-02-13 09:42 UTC, neSpecc approved these changes

2018-02-13 09:43 UTC, merged